services:
  db:
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  prestart:
    image: '${DOCKER_IMAGE?Variable not set}:${TAG:-latest}'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env
