"""

Revision ID: 4d932fd3bd66
Revises: ae6b6519ef2b
Create Date: 2025-08-17 15:31:41.402666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d932fd3bd66'
down_revision: Union[str, Sequence[str], None] = 'ae6b6519ef2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_minute_trade_latencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloud_instance_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('average_trade_latency', sa.Float(), nullable=False),
    sa.Column('min_trade_latency', sa.Float(), nullable=False),
    sa.Column('max_trade_latency', sa.Float(), nullable=False),
    sa.Column('total_trade_volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_instance_id'], ['cloud_instances.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_minute_trade_latencies_id'), 'historical_minute_trade_latencies', ['id'], unique=False)
    op.drop_index(op.f('ix_historicalminutetradelatencies_id'), table_name='historicalminutetradelatencies')
    op.drop_table('historicalminutetradelatencies')
    op.drop_table('cloudinstances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudinstances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cloudinstances_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cloudinstances_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('historicalminutetradelatencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cloud_instance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('average_trade_latency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_trade_latency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_trade_latency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_trade_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cloud_instance_id'], ['cloudinstances.id'], name=op.f('historicalminutetradelatencies_cloud_instance_id_fkey')),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('historicalminutetradelatencies_exchange_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historicalminutetradelatencies_pkey'))
    )
    op.create_index(op.f('ix_historicalminutetradelatencies_id'), 'historicalminutetradelatencies', ['id'], unique=False)
    op.drop_index(op.f('ix_historical_minute_trade_latencies_id'), table_name='historical_minute_trade_latencies')
    op.drop_table('historical_minute_trade_latencies')
    op.drop_table('cloud_instances')
    # ### end Alembic commands ###
