"""Renames aggregation field

Revision ID: ae6b6519ef2b
Revises: b3d44be74c52
Create Date: 2025-08-11 14:03:00.910776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6b6519ef2b'
down_revision: Union[str, Sequence[str], None] = 'b3d44be74c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicalminutetradelatencies', sa.Column('total_trade_volume', sa.Float(), nullable=False))
    op.drop_column('historicalminutetradelatencies', 'average_trade_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicalminutetradelatencies', sa.Column('average_trade_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('historicalminutetradelatencies', 'total_trade_volume')
    # ### end Alembic commands ###
