"""Initial migration

Revision ID: b3d44be74c52
Revises: 
Create Date: 2025-08-07 13:03:56.392345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d44be74c52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudinstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('server_location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicalminutetradelatencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloud_instance_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('average_trade_latency', sa.Float(), nullable=False),
    sa.Column('min_trade_latency', sa.Float(), nullable=False),
    sa.Column('max_trade_latency', sa.Float(), nullable=False),
    sa.Column('average_trade_volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_instance_id'], ['cloudinstances.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicalminutetradelatencies_id'), 'historicalminutetradelatencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historicalminutetradelatencies_id'), table_name='historicalminutetradelatencies')
    op.drop_table('historicalminutetradelatencies')
    op.drop_table('exchanges')
    op.drop_table('cloudinstances')
    # ### end Alembic commands ###
