"""Adds coordinates for cloud instances

Revision ID: b59457bec544
Revises: 51cfec6f622b
Create Date: 2025-09-29 14:20:35.184053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59457bec544'
down_revision: Union[str, Sequence[str], None] = '51cfec6f622b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_instances', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('cloud_instances', sa.Column('latitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_instances', 'latitude')
    op.drop_column('cloud_instances', 'longitude')
    # ### end Alembic commands ###
